// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crjvvwpycfhztzhiasib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyanZ2d3B5Y2ZoenR6aGlhc2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjM0MzcsImV4cCI6MjA2NzQ5OTQzN30.2bfMX_oGmuLoiXeNExKBv5wwE7DvBG-Q4tNmk5iLiMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});